services:
  - type: web
    name: elonuz-marketplace
    env: node
    region: frankfurt
    plan: free
    rootDir: .
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: ElonUZ_JWT_Secret_2026_Secure!
      - key: PORT
        value: 10000
    disk:
      name: elonuz-data
      mountPath: /opt/render/project/src/server
      sizeGB: 1
